-- Online Retail SQL Analysis
-- 02 - Sales Analysis

-- What is the total revenue generated by the dataset?
SELECT SUM(Quantity*UnitPrice) AS TotalRevenue
FROM dbo.OnlineRetail

-- Duplicate row investigation
-- Exact duplicate rows were found in the dataset.
-- Inspection of several affected invoices showed repeated products and quantities
-- that appear consistent with legitimate transaction activity rather than obvious
-- database duplication.
-- Therefore, the original rows are retained for analysis rather than removed.
SELECT
	SUM(Quantity*UnitPrice) AS RevenueWithoutDuplicates
FROM (
	SELECT 
		*,
		ROW_NUMBER() OVER(
			PARTITION BY 
				InvoiceNo, 
				Stockcode, 
				Description, 
				Quantity, 
				UnitPrice, 
				CustomerID, 
				Country, 
				InvoiceDate 
			ORDER BY (SELECT NULL)
		) AS CopyNo
	FROM dbo.OnlineRetail
) AS RowTable
WHERE CopyNo = 1;

SELECT 
	COUNT(DISTINCT InvoiceNo) AS DistinctInvoicesWithDuplicates
FROM (
	SELECT 
		*,
		ROW_NUMBER() OVER(
			PARTITION BY 
				InvoiceNo, 
				Stockcode, 
				Description, 
				Quantity, 
				UnitPrice, 
				CustomerID, 
				Country, 
				InvoiceDate 
			ORDER BY (SELECT NULL)
		) AS CopyNo
	FROM dbo.OnlineRetail
) AS RowTable
WHERE CopyNo > 1;

SELECT
	InvoiceNo,
	COUNT(*) AS NumberOfDupes
FROM (
	SELECT 
		*,
		ROW_NUMBER() OVER(
			PARTITION BY 
				InvoiceNo, 
				Stockcode, 
				Description, 
				Quantity, 
				UnitPrice, 
				CustomerID, 
				Country, 
				InvoiceDate 
			ORDER BY (SELECT NULL)
		) AS CopyNo
	FROM dbo.OnlineRetail
) AS RowTable
WHERE CopyNo > 1
GROUP BY InvoiceNo
ORDER BY COUNT(*) DESC;

-- Invoice 555524
-- Several products, including teacup and saucer items, appear as repeated rows
-- with a quantity of 1. This is consistent with a customer purchasing multiple
-- individual items rather than an obvious database duplication error.
SELECT *
FROM dbo.OnlineRetail
WHERE InvoiceNo = '555524';

-- Invoice 572861
-- Multiple drawer knob products appear in repeated rows with quantities of 6,
-- 12, and 36, alongside other products with smaller quantities.
-- The repeated quantities appear consistent with a larger customer order
-- rather than an obvious database duplication error.
SELECT *
FROM dbo.OnlineRetail
WHERE InvoiceNo = '572861'
ORDER BY StockCode;