-- Online Retail SQL Analysis
-- 02 - Sales Analysis

-- What is the total revenue generated by the dataset?
SELECT SUM(Quantity*UnitPrice) AS TotalRevenue
FROM dbo.OnlineRetail;

-- Duplicate row investigation
-- Exact duplicate rows were found in the dataset.
-- Inspection of several affected invoices showed repeated products and quantities
-- that appear consistent with legitimate transaction activity rather than obvious
-- database duplication.
-- Therefore, the original rows are retained for analysis rather than removed.
SELECT
	SUM(Quantity*UnitPrice) AS RevenueWithoutDuplicates
FROM (
	SELECT 
		*,
		ROW_NUMBER() OVER(
			PARTITION BY 
				InvoiceNo, 
				Stockcode, 
				Description, 
				Quantity, 
				UnitPrice, 
				CustomerID, 
				Country, 
				InvoiceDate 
			ORDER BY (SELECT NULL)
		) AS CopyNo
	FROM dbo.OnlineRetail
) AS RowTable
WHERE CopyNo = 1;

SELECT 
	COUNT(DISTINCT InvoiceNo) AS DistinctInvoicesWithDuplicates
FROM (
	SELECT 
		*,
		ROW_NUMBER() OVER(
			PARTITION BY 
				InvoiceNo, 
				Stockcode, 
				Description, 
				Quantity, 
				UnitPrice, 
				CustomerID, 
				Country, 
				InvoiceDate 
			ORDER BY (SELECT NULL)
		) AS CopyNo
	FROM dbo.OnlineRetail
) AS RowTable
WHERE CopyNo > 1;

SELECT
	InvoiceNo,
	COUNT(*) AS NumberOfDupes
FROM (
	SELECT 
		*,
		ROW_NUMBER() OVER(
			PARTITION BY 
				InvoiceNo, 
				Stockcode, 
				Description, 
				Quantity, 
				UnitPrice, 
				CustomerID, 
				Country, 
				InvoiceDate 
			ORDER BY (SELECT NULL)
		) AS CopyNo
	FROM dbo.OnlineRetail
) AS RowTable
WHERE CopyNo > 1
GROUP BY InvoiceNo
ORDER BY COUNT(*) DESC;

-- Invoice 555524
-- Several products, including teacup and saucer items, appear as repeated rows
-- with a quantity of 1. This is consistent with a customer purchasing multiple
-- individual items rather than an obvious database duplication error.
SELECT *
FROM dbo.OnlineRetail
WHERE InvoiceNo = '555524';

-- Invoice 572861
-- Multiple drawer knob products appear in repeated rows with quantities of 6,
-- 12, and 36, alongside other products with smaller quantities.
-- The repeated quantities appear consistent with a larger customer order
-- rather than an obvious database duplication error.
SELECT *
FROM dbo.OnlineRetail
WHERE InvoiceNo = '572861'
ORDER BY StockCode;

-- Cancellation Investigation
SELECT
	COUNT(DISTINCT InvoiceNo) AS NumberOfCancelledInvoices,
	COUNT(*) AS NumberOfCancellationRows,
	SUM(Quantity*UnitPrice) AS TotalCancellationValue
FROM dbo.OnlineRetail
WHERE InvoiceNo LIKE 'C%';

SELECT
    COUNT(DISTINCT 
			CASE 
				WHEN InvoiceNo LIKE 'C%' 
				THEN InvoiceNo 
			END) * 100.0
        / COUNT(DISTINCT InvoiceNo) AS CancellationRate
FROM dbo.OnlineRetail;

SELECT
    ABS(
        SUM(CASE 
                WHEN InvoiceNo LIKE 'C%' 
                THEN Quantity * UnitPrice 
                ELSE 0 
            END)
    ) * 100.0
    / SUM(CASE 
            WHEN InvoiceNo LIKE 'C%' 
            THEN 0 
            ELSE Quantity * UnitPrice 
        END) AS CancellationValuePctOfNonCancelledValue
FROM dbo.OnlineRetail;

-- Monthly Breakdown
SELECT
	Year,
	Month,
	MonthlyInvoices,
	ItemsSold,
	ItemsSold / NULLIF(MonthlyInvoices, 0) AS AvgItemsPerInvoice,
	MonthlyRevenue,
	MonthlyRevenue / NULLIF(MonthlyInvoices, 0) AS AvgRevPerInvoice
FROM (
	SELECT 
		YEAR(InvoiceDate) AS Year,
		MONTH(InvoiceDate) AS Month,
		SUM(
			CASE 
				WHEN InvoiceNo LIKE 'C%' THEN 0 
				ELSE Quantity 
			END
		) AS ItemsSold,
		SUM(
			CASE 
				WHEN InvoiceNo LIKE 'C%' THEN 0
				ELSE Quantity * UnitPrice
			END
		) AS MonthlyRevenue,
		COUNT(DISTINCT 
			CASE 
				WHEN InvoiceNo NOT LIKE 'C%' THEN InvoiceNo
			END
		) AS MonthlyInvoices 
	FROM dbo.OnlineRetail
	GROUP BY	
		MONTH(InvoiceDate),
		YEAR(InvoiceDate)
) AS MonthlyBreakdown
ORDER BY 
	Year ASC,
	Month ASC;

-- Customer Analysis
SELECT
	CustomerID,
	RevenuePerCustomer,
	InvoicesPerCustomer,
	RevenuePerCustomer/InvoicesPerCustomer AS RevenuePerInvoicePerCustomer
FROM (
	SELECT
		CustomerID,
		SUM(Quantity*UnitPrice) AS RevenuePerCustomer,
		COUNT(DISTINCT InvoiceNo) AS InvoicesPerCustomer
	FROM dbo.OnlineRetail
	WHERE CustomerID IS NOT NULL 
		AND InvoiceNo NOT LIKE 'C%'
	GROUP BY CustomerID
) AS CustomerBreakdown
ORDER BY RevenuePerInvoicePerCustomer DESC;

SELECT
InvoicesPerCustomer,
COUNT(CustomerID) CustomersPerInvoice
FROM (
SELECT 
	CustomerID,
	COUNT(DISTINCT InvoiceNo) AS InvoicesPerCustomer
	FROM dbo.OnlineRetail
	WHERE CustomerID IS NOT NULL 
		AND InvoiceNo NOT LIKE 'C%'
	GROUP BY CustomerID
) AS i
GROUP BY InvoicesPerCustomer
ORDER BY InvoicesPerCustomer;

SELECT TOP 10
	CustomerID,
	InvoicesPerCustomer,
	ItemsPurchased,
	ItemsPurchased*1.0/InvoicesPerCustomer AS ItemsPerInvoicePerCustomer,
	RevenuePerCustomer,
	RevenuePerCustomer*1.0/ItemsPurchased AS RevenuePerItemPerCustomer,
	RevenuePerCustomer*1.0/InvoicesPerCustomer AS RevenuePerInvoicePerCustomer
FROM (
	SELECT
		CustomerID,
		SUM(Quantity*UnitPrice) AS RevenuePerCustomer,
		COUNT(DISTINCT InvoiceNo) AS InvoicesPerCustomer,
		SUM(Quantity) AS ItemsPurchased
	FROM dbo.OnlineRetail
	WHERE CustomerID IS NOT NULL 
		AND InvoiceNo NOT LIKE 'C%'
	GROUP BY CustomerID
) AS CustomerBreakdown
WHERE InvoicesPerCustomer > 20
ORDER BY RevenuePerInvoicePerCustomer ASC;

-- Invoice Number Group Analysis
SELECT
	InvoiceGroup,
	COUNT(*) AS Customers,
	SUM(RevenuePerCustomer) AS TotalRevenue,
	SUM(RevenuePerCustomer)*1.0/COUNT(*) AS RevenuePerCustomer,
	SUM(ItemsPurchased) AS TotalItems,
	SUM(InvoicesPerCustomer) AS TotalInvoices,
	SUM(ItemsPurchased)*1.0/SUM(InvoicesPerCustomer) AS ItemsPerInvoice,
	SUM(RevenuePerCustomer)*1.0/SUM(ItemsPurchased) AS RevenuePerItem,
	SUM(InvoicesPerCustomer)*1.0/COUNT(*) AS AvgInvoicesPerCustomer
FROM (
	SELECT
		CustomerID,
		RevenuePerCustomer,
		InvoicesPerCustomer,
		ItemsPurchased,
		(CASE 
			WHEN InvoicesPerCustomer <=5 THEN '1-5'
			WHEN InvoicesPerCustomer <=10 THEN '6-10'
			WHEN InvoicesPerCustomer <=20 THEN '11-20'
			WHEN InvoicesPerCustomer <=50 THEN '21-50'
			ELSE '50+'
		END) AS InvoiceGroup,
		(CASE 
			WHEN InvoicesPerCustomer <=5 THEN 1
			WHEN InvoicesPerCustomer <=10 THEN 2
			WHEN InvoicesPerCustomer <=20 THEN 3
			WHEN InvoicesPerCustomer <=50 THEN 4
			ELSE 5
		END) AS SortOrder
	FROM (
		SELECT
			CustomerID,
			SUM(Quantity*UnitPrice) AS RevenuePerCustomer,
			COUNT(DISTINCT InvoiceNo) AS InvoicesPerCustomer,
			SUM(Quantity) AS ItemsPurchased
		FROM dbo.OnlineRetail
		WHERE CustomerID IS NOT NULL 
			AND InvoiceNo NOT LIKE 'C%'
		GROUP BY CustomerID
	) AS CustomerMetrics
) AS CustomerGroups
GROUP BY InvoiceGroup, SortOrder
ORDER BY SortOrder ASC;